#!/usr/bin/env python3
"""Refresh packaged notices after building libengine.so or changing go.mod."""
import json
from pathlib import Path
import subprocess

root = Path(__file__).resolve().parent.parent


def go(*args):
    return subprocess.check_output(["go", *args], cwd=root / "engine-go", text=True)


raw = go("list", "-m", "-json", "all")
decoder = json.JSONDecoder()
modules = {}
while raw.strip():
    raw = raw.lstrip()
    module, end = decoder.raw_decode(raw)
    modules[module["Path"]] = module
    raw = raw[end:]

binary = root / "android/app/src/main/jniLibs/arm64-v8a/libengine.so"
linked = [line.split()[1] for line in go("version", "-m", str(binary)).splitlines()
          if line.lstrip().startswith("dep\t")]
if not linked:
    raise SystemExit("Build libengine.so before updating notices.")
notices = ["Third-party notices for the native Go engine.\n"
           "Generated by scripts/update-go-notices.py from linked modules.\n"
           "Versions and checksums: engine-go/go.mod and engine-go/go.sum.\n"]
for name in sorted(linked):
    module = modules[name]
    folder = Path(module.get("Replace", module)["Dir"])
    files = sorted(p for p in folder.iterdir() if p.is_file()
                   and p.name.lower().startswith(("license", "licence", "copying", "notice")))
    if not files:
        raise SystemExit(f"No license found for {name}; inspect its source.")
    for file in files:
        notices.append(f"\n{'=' * 72}\n{name} {module.get('Version', '')} — {file.name}\n\n"
                       + file.read_text())
go_license = next((p for p in [Path(go("env", "GOROOT").strip()) / "LICENSE",
                               Path("/usr/share/licenses/go/LICENSE")] if p.is_file()), None)
if go_license is None:
    raise SystemExit("Locate the Go runtime LICENSE before distributing.")
notices.append(f"\n{'=' * 72}\nGo runtime license\n\n" + go_license.read_text())
output = root / "android/app/src/main/assets/licenses/go-dependencies.txt"
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text("\n".join(notices))
print(f"Packaged notices for {len(linked)} modules ({output.stat().st_size} bytes).")
